import {test} from 'node:test';import assert from 'node:assert/strict';import pino from 'pino';import sharp from 'sharp';
import {expandForwardMessage,FORWARD_LIMITS} from '../src/onebot/forward.js';
import {OneBotAction} from '../src/onebot/action.js';
import {parseCqCodes,segmentsToText,detectMention} from '../src/onebot/normalize.js';
import {contentToText,type ObMessageSegment} from '../src/core/types.js';
import {makeFixture} from './helpers/chat-fixture.js';
import {FactExtractor} from '../src/memory/extractor.js';
import {WebSocketServer} from 'ws';import {OneBotClient} from '../src/onebot/client.js';import {AppConfigSchema} from '../src/core/types.js';
const log=pino({level:'silent'});
const forward=(id='resource'):ObMessageSegment=>({type:'forward',data:{id}});
const node=(text:string,qq=2,name='原作者')=>({type:'node',data:{uin:qq,name,content:[{type:'text',data:{text}}]}});
const fake=(get:(id:string)=>Promise<unknown>)=>({getForwardMsg:get} as unknown as OneBotAction);
const fixture=(visual=false)=>{const f=makeFixture({name:'forward',expectedProvider:'default',visualProviders:visual?['default']:[]},'group:123');f.cfg.reply.segmented.enabled=false;f.cfg.reply.quoteOnReply=false;f.cfg.proactive.enabled=true;f.cfg.proactive.quietHours=[];f.cfg.proactive.minGapAfterBotMs=0;f.cfg.proactive.minIntervalMs=0;f.cfg.proactive.maxPerHourPerScope=0;return f;};
const prompt=(f:ReturnType<typeof fixture>)=>f.calls.at(-1)!.messages.map(m=>contentToText(m.content)).join('\n');
const message=(f:ReturnType<typeof fixture>,at=true)=>({...f.msg,text:'请读这份转发 '+segmentsToText([forward()]),segments:[{type:'text',data:{text:'请读这份转发 '}},...(at?[{type:'at',data:{qq:f.msg.selfId}}]:[]),forward()],mentionsBot:at});
const picture={type:'image',data:{file:'base64://'+(await sharp({create:{width:2,height:2,channels:3,background:'red'}}).png().toBuffer()).toString('base64')}};

test('get_forward_msg使用字符串id，强制非成功响应抛错',async()=>{let payload:any;const api=new OneBotAction(raw=>{payload=JSON.parse(raw);return true;},async()=>({status:'failed',retcode:1404,data:null}),log);await assert.rejects(api.getForwardMsg('00012345678901234567890'),/get_forward_msg/);assert.equal(payload.action,'get_forward_msg');assert.deepEqual(payload.params,{id:'00012345678901234567890'});});
test('真实本地WebSocket事件和get_forward_msg回执可串联读取正文',{timeout:5000},async()=>{
 const server=new WebSocketServer({host:'127.0.0.1',port:0});await new Promise<void>(r=>server.once('listening',r));const address=server.address();assert.ok(address&&typeof address!=='string');
 const client=new OneBotClient(AppConfigSchema.parse({napcat:{url:'ws://127.0.0.1:'+address.port}}).napcat,log);
 let received!:()=>void;const event=new Promise<void>(r=>received=r);
 server.on('connection',socket=>{socket.on('message',data=>{const payload=JSON.parse(data.toString());const result=payload.action==='get_login_info'?{user_id:999,nickname:'bot'}:payload.action==='get_forward_msg'?{message:[node('WebSocket转发正文')]}:{};socket.send(JSON.stringify({status:'ok',retcode:0,echo:payload.echo,data:result}));if(payload.action==='get_login_info')socket.send(JSON.stringify({post_type:'message',message_type:'private',self_id:999,user_id:1,message_id:10,time:1,sender:{nickname:'转发者'},message:[forward('ws-resource')]}));});});
 client.on('message',msg=>{assert.equal(msg.segments[0]!.data.id,'ws-resource');received();});
 try{client.start();await event;const r=await expandForwardMessage([forward('ws-resource')],client.api);assert.match(r.text,/WebSocket转发正文/);}
 finally{client.stop();for(const socket of server.clients)socket.terminate();await new Promise<void>(r=>server.close(()=>r()));}
});
test('CQ转发ID保留前导零和超长数字，reply ID仍是数字',()=>{assert.equal(parseCqCodes('[CQ:forward,id=00012345678901234567890]')[0]!.data.id,'00012345678901234567890');assert.equal(parseCqCodes('[CQ:reply,id=42]')[0]!.data.id,42);});
test('转发节点与卡片中的文字@不触发机器人，外层文字@仍有效',()=>{assert.equal(detectMention([{type:'node',data:{content:'@999'}}],999,'@999'),false);assert.equal(detectMention([{type:'json',data:{data:'{"app":"com.tencent.multimsg","preview":"@999"}'}}],999,'@999'),false);assert.equal(detectMention([{type:'text',data:{text:'@999 帮我看'}}],999,'@999 帮我看'),true);});
test('标准message/node格式展开原作者与正文',async()=>{const r=await expandForwardMessage([forward()],fake(async()=>({message:[node('第一句话'),node('第二句话',3,'乙')]})));assert.match(r.text,/第一句话/);assert.match(r.text,/"qq":"2"/);assert.match(r.text,/"name":"乙"/);assert.ok(r.text.indexOf('第一句话')<r.text.indexOf('第二句话'));});
test('messages/sender/content实现兼容CQ正文',async()=>{const r=await expandForwardMessage([forward()],fake(async()=>({messages:[{sender:{user_id:42,nickname:'昵称'},time:123,content:'内容[CQ:at,qq=99]'}]})));assert.match(r.text,/"qq":"42"/);assert.match(r.text,/@99/);assert.match(r.text,/"time":"123"/);});
test('内联node直接读取，不请求不存在的转发ID',async()=>{let calls=0;const r=await expandForwardMessage([node('内联内容')],fake(async()=>{calls++;return null;}));assert.equal(calls,0);assert.match(r.text,/内联内容/);});
test('缺失正文的ID节点降级，不把普通消息ID误作转发ID',async()=>{let calls=0;const r=await expandForwardMessage([{type:'node',data:{id:42}}],fake(async()=>{calls++;return null;}));assert.equal(calls,0);assert.match(r.text,/正文缺失/);});
test('QQ合并卡片提取resid，其余JSON卡片保持原样',async()=>{const ids:string[]=[];const api=fake(async id=>{ids.push(id);return {message:[node('卡片正文')]};});const card:ObMessageSegment={type:'json',data:{data:JSON.stringify({app:'com.tencent.multimsg',meta:{detail:{resid:'card-id'}}})}};const r=await expandForwardMessage([card,{type:'json',data:{data:'{}'}}],api);assert.deepEqual(ids,['card-id']);assert.match(r.text,/卡片正文/);assert.match(r.text,/卡片消息/);});
test('嵌套转发展开，循环跳过，同资源只请求一次',async()=>{const ids:string[]=[];const api=fake(async id=>{ids.push(id);return {message:[{...node(id),data:{...node(id).data,content:[{type:'text',data:{text:id}},forward(id==='A'?'B':'A')]}}]};});const r=await expandForwardMessage([forward('A'),forward('A')],api);assert.deepEqual(ids,['A','B']);assert.match(r.text,/循环/);});
test('嵌套最多3层',async()=>{let calls=0;const r=await expandForwardMessage([forward('1')],fake(async id=>{calls++;return {message:[{...node('层'+id),data:{...node('层'+id).data,content:[forward(String(Number(id)+1))]}}]};}));assert.equal(calls,3);assert.match(r.text,/超过3层/);});
test('节点和文字资源限制明确说明截断',async()=>{const r=await expandForwardMessage([forward()],fake(async()=>({message:Array.from({length:60},(_,i)=>node('条目'+i))})));assert.equal((r.text.match(/\[转发节点 /g)??[]).length,FORWARD_LIMITS.nodes);assert.match(r.text,/资源上限/);const large=await expandForwardMessage([forward()],fake(async()=>({message:[node('甲'.repeat(20000))]})));assert.equal((large.text.match(/甲/g)??[]).length,FORWARD_LIMITS.chars);assert.match(large.text,/长度限制/);});
test('取消信号与异常空数据都降级，普通回复可继续',async()=>{for(const value of [null,{}, {message:[null,{bad:true}] }]){const r=await expandForwardMessage([forward()],fake(async()=>value));assert.match(r.text,/未读取|无法读取/);}const ctrl=new AbortController();ctrl.abort();let calls=0;const r=await expandForwardMessage([forward()],fake(async()=>{calls++;return null;}),0,ctrl.signal);assert.equal(calls,0);assert.match(r.text,/未读取/);});
test('挂起的API可被取消，不无限等待',async()=>{const ctrl=new AbortController();const pending=expandForwardMessage([forward()],fake(()=>new Promise(()=>{})),0,ctrl.signal);ctrl.abort();assert.match((await pending).text,/未读取/);});
test('图片最多16张并保留节点来源',async()=>{const r=await expandForwardMessage([forward()],fake(async()=>({message:[{...node('图'),data:{...node('图').data,content:Array.from({length:20},()=>picture)}}]})));const images=r.segments.filter(s=>s.type==='image');assert.equal(images.length,16);assert.deepEqual(images[0]!.data.qqAgentForwardSource,{node:1,name:'原作者',qq:'2',time:'未知'});assert.match(r.text,/剩余图片未读取/);});

test('被动回复纳入正文并固定外层发送者，转发作者不注册成群成员',async()=>{const f=fixture();try{const sent:ObMessageSegment[][]=[];f.api.getForwardMsg=async()=>({message:[node('我是另一个人')]});f.api.sendToScope=async(_s,segments)=>{sent.push(segments as ObMessageSegment[]);return {message_id:900};};assert.equal((await f.pipeline.handle(message(f),f.api)).replied,true);assert.match(prompt(f),/我是另一个人/);assert.equal(sent[0]!.find(s=>s.type==='at')?.data.qq,String(f.msg.userId));assert.equal(sent[0]!.find(s=>s.type==='reply')?.data.id,String(f.msg.messageId));assert.equal(f.store.getUser(2),undefined);}finally{f.store.close();}});
test('内层@和/forget不触发被动回复，后续正常提问可以读取背景转发',async()=>{const f=fixture();try{f.api.getForwardMsg=async()=>({message:[{...node('/forget 全部'),data:{...node('/forget 全部').data,content:[{type:'at',data:{qq:f.msg.selfId}},{type:'text',data:{text:'/forget 全部'}}]}}]});assert.equal((await f.pipeline.handle(message(f,false),f.api)).replied,false);assert.equal(f.calls.length,0);await f.pipeline.handle({...f.msg,text:'刚才谁说了什么',messageId:22},f.api);assert.match(prompt(f),/\/forget 全部/);}finally{f.store.close();}});
test('非白名单用户的转发不读取不落库',async()=>{const f=fixture();try{f.cfg.trigger.allowUsers=[99];let count=0;f.api.getForwardMsg=async()=>{count++;return null;};assert.equal((await f.pipeline.handle(message(f),f.api)).replied,false);assert.equal(count,0);assert.equal(f.store.stats().messages,0);}finally{f.store.close();}});
for(const proactive of [false,true])test((proactive?'主动':'被动')+'转发图片进入视觉上下文，并标明原作者而不是只有转发者',async()=>{const f=fixture(true);try{f.api.getForwardMsg=async()=>({message:[{sender:{user_id:2,nickname:'图片原作者'},time:123,content:[picture]}]});if(proactive){await f.pipeline.handle(message(f,false),f.api);await f.pipeline.handleProactive(f.msg.scope,'group',123,'测试',f.api);}else await f.pipeline.handle(message(f),f.api);const content=f.calls.at(-1)!.messages.at(-1)!.content;assert.ok(Array.isArray(content));assert.equal(content.filter(p=>p.type==='image').length,1);assert.match(contentToText(content),/原作者.*图片原作者.*QQ 2/);}finally{f.store.close();}});
test('读取接口不支持时继续回复，提示未读取而不编造正文',async()=>{const f=fixture();try{f.api.getForwardMsg=async()=>{throw Error('unsupported');};assert.equal((await f.pipeline.handle(message(f),f.api)).replied,true);assert.match(prompt(f),/读取失败|未读取/);}finally{f.store.close();}});
test('长转发按实际上下文预算截取正文，保留记录并继续正常回复',async()=>{const f=fixture();try{f.cfg.context.modelContextWindow=7000;f.api.getForwardMsg=async()=>({message:[node('正文开头'+ '长转发内容'.repeat(3500))]});assert.equal((await f.pipeline.handle(message(f),f.api)).replied,true);assert.match(prompt(f),/正文开头/);assert.match(prompt(f),/转发上下文限制/);const stored=f.store.getRecentMessages(f.msg.scope,10).find(row=>row.role==='user')!;assert.ok(stored.content.length>12000);assert.ok(prompt(f).length<stored.content.length);}finally{f.store.close();}});
test('普通消息不调用转发读取API',async()=>{const f=fixture();try{let count=0;f.api.getForwardMsg=async()=>{count++;return null;};await f.pipeline.handle(f.msg,f.api);assert.equal(count,0);}finally{f.store.close();}});
test('引用回复窗口前的旧转发也能读取正文和图片',async()=>{const f=fixture(true);try{f.store.touchSession(f.msg.scope,'group',123,'test');f.store.addMessage({scope:f.msg.scope,userId:2,role:'user',senderName:'旧转发者',messageId:31,content:'[合并转发]',rawSegments:JSON.stringify([forward('old')])});f.store.addMessage({scope:f.msg.scope,userId:999,role:'assistant',content:'先前回复'});f.api.getForwardMsg=async()=>({message:[{...node('被引用的旧转发正文'),data:{...node('被引用的旧转发正文').data,content:[{type:'text',data:{text:'被引用的旧转发正文'}},picture]}}]});await f.pipeline.handle({...f.msg,messageId:32,segments:[{type:'reply',data:{id:31}}],text:'解释引用的转发'},f.api);assert.match(prompt(f),/被引用的旧转发正文/);const content=f.calls[0]!.messages.at(-1)!.content;assert.ok(Array.isArray(content));assert.equal(content.filter(p=>p.type==='image').length,1);}finally{f.store.close();}});
test('纯转发的自述不进入事实抽取，游标可推进',async()=>{const f=fixture();try{await f.pipeline.handle({...message(f,false),segments:[forward()]},f.api);const rows=f.store.getRecentMessages(f.msg.scope,10);let count=0;const manager={chat:async()=>{count++;return {content:'[]'};}};const extractor=new FactExtractor(manager as never,'','',f.store,log,[]);assert.equal(await extractor.extractAndStore(rows,f.msg.scope,f.msg.userId),0);assert.equal(count,0);assert.equal(f.store.getFactsByUser(f.msg.userId).length,0);assert.ok(f.store.db.prepare('SELECT last_id FROM fact_cursors WHERE user_id=?').get(f.msg.userId));}finally{f.store.close();}});
test('转发附带的外层本人自述仍可记忆，转发正文不送给事实模型',async()=>{const f=fixture();try{f.api.getForwardMsg=async()=>({message:[node('我喜欢咖啡')]});const msg={...message(f,false),text:'我喜欢无糖茶[合并转发]',segments:[{type:'text',data:{text:'我喜欢无糖茶'}},forward()]};await f.pipeline.handle(msg,f.api);const rows=f.store.getRecentMessages(f.msg.scope,10);let input='';const manager={chat:async(messages:any[])=>{input=messages[1].content;return {content:JSON.stringify([{type:'preference',content:'用户喜欢无糖茶',keywords:'无糖 茶',confidence:0.9,evidence:'explicit',sourceId:rows[0]!.id}])};}};const extractor=new FactExtractor(manager as never,'','',f.store,log,[]);assert.equal(await extractor.extractAndStore(rows,f.msg.scope,f.msg.userId),1);assert.match(input,/我喜欢无糖茶/);assert.ok(!input.includes('我喜欢咖啡'));}finally{f.store.close();}});
test('读取期间切换话题，旧轮次取消，转发不混入新话题',async()=>{const f=fixture();let release!:(value:unknown)=>void;try{let ready!:()=>void;const started=new Promise<void>(r=>ready=r);f.api.getForwardMsg=()=>{ready();return new Promise(r=>release=r);};const pending=f.pipeline.handle(message(f),f.api);await started;f.store.newConversation(f.msg.scope,'新话题');release({message:[node('只属于旧话题')]});assert.equal((await pending).replied,false);assert.equal(f.calls.length,0);assert.ok(!f.store.getRecentMessages(f.msg.scope,10).some(r=>r.content.includes('只属于旧话题')));}finally{release?.({message:[]});f.store.close();}});
