import {test} from 'node:test';import assert from 'node:assert/strict';import sharp from 'sharp';
import {makeFixture} from './helpers/chat-fixture.js';import {contentToText} from '../src/core/types.js';
import type {ObMessageSegment} from '../src/core/types.js';
import {captureReplyWindow} from '../src/pipeline/window.js';
const pictures=await Promise.all(['red','blue','green','yellow','purple'].map(async color=>({type:'image',data:{file:'base64://'+(await sharp({create:{width:2,height:2,channels:3,background:color}}).png().toBuffer()).toString('base64')}} as ObMessageSegment)));
function fixture(visual=false){const f=makeFixture({name:'window',expectedProvider:'default',visualProviders:visual?['default']:[]},'group:123');f.cfg.reply.segmented.enabled=false;f.cfg.reply.quoteOnReply=false;f.cfg.proactive.enabled=true;f.cfg.proactive.quietHours=[];f.cfg.proactive.minGapAfterBotMs=0;f.cfg.proactive.minIntervalMs=0;f.cfg.proactive.maxPerHourPerScope=0;const payloads:ObMessageSegment[][]=[];f.api.sendToScope=async(_s,p)=>{payloads.push(p as ObMessageSegment[]);return {message_id:900+payloads.length};};return {...f,payloads};}
function add(f:ReturnType<typeof fixture>,text:string,userId=2,messageId=20,segments:ObMessageSegment[]=[]){f.store.touchSession(f.msg.scope,'group',123,'test');return f.store.addMessage({scope:f.msg.scope,userId,role:'user',content:text,senderName:'群友'+userId,messageId,rawSegments:JSON.stringify(segments)});}
const input=(f:ReturnType<typeof fixture>,i=0)=>f.calls[i]!.messages.map(m=>contentToText(m.content)).join('\n');
function deferred(){let release!:()=>void;const promise=new Promise<void>(r=>release=r);return {promise,release};}
for(const proactive of [false,true])test((proactive?'主动':'被动')+'纳入上次回复后完整窗口，不受recentTurns及摘要状态限制',async()=>{const f=fixture();try{f.store.touchSession(f.msg.scope,'group',123,'test');f.store.addMessage({scope:f.msg.scope,userId:999,role:'assistant',content:'上一次机器人回复'});f.cfg.memory.recentTurns=1;f.cfg.memory.summary.enabled=true;for(let i=0;i<55;i++){const id=add(f,'窗口条目-'+i,2,100+i);f.store.db.prepare('UPDATE messages SET summarized=1 WHERE id=?').run(id);}if(proactive)await f.pipeline.handleProactive(f.msg.scope,'group',123,'测试',f.api);else await f.pipeline.handle({...f.msg,text:'请回答窗口问题',messageId:300},f.api);const prompt=input(f);for(let i=0;i<55;i++)assert.ok(prompt.includes('窗口条目-'+i+'\n')||prompt.includes('窗口条目-'+i),String(i));const log=f.logs.find(l=>l.msg==='上下文已构建')!;assert.equal(log.replyWindowMessages,proactive?55:56);}finally{f.store.close();}});
test('关闭旧recordAllMessages选项仍记录允许群聊，拒绝用户不混入窗口',async()=>{const f=fixture();try{f.cfg.trigger.group.recordAllMessages=false;await f.pipeline.handle({...f.msg,userId:2,senderName:'甲',mentionsBot:false,messageId:21,text:'需要保留的聊天'},f.api);f.cfg.trigger.denyUsers=[3];await f.pipeline.handle({...f.msg,userId:3,mentionsBot:false,messageId:22,text:'黑名单内容'},f.api);await f.pipeline.handle({...f.msg,messageId:23,text:'回答'},f.api);assert.ok(input(f).includes('需要保留的聊天'));assert.ok(!input(f).includes('黑名单内容'));}finally{f.store.close();}});
test('排队期间新聊天被纳入，但触发者和触发消息保持固定',async()=>{const f=fixture();const gate=deferred(),ready=deferred();try{const blocker=(f.pipeline as any).enqueue(f.msg.scope,async()=>{ready.release();await gate.promise;});await ready.promise;const pending=f.pipeline.handle({...f.msg,text:'原始提问',messageId:301},f.api);await f.pipeline.handle({...f.msg,userId:2,senderName:'乙',mentionsBot:false,messageId:302,text:'队列等待中出现'},f.api);gate.release();await blocker;await pending;assert.ok(input(f).includes('队列等待中出现'));assert.match(input(f),/本轮被动回复对象固定为 .*"qq":1,"messageId":301/);assert.match(input(f),/群友|乙/);assert.equal(f.payloads[0]!.find(s=>s.type==='at')?.data.qq,'1');assert.equal(f.payloads[0]!.find(s=>s.type==='reply')?.data.id,'301');}finally{gate.release();f.store.close();}});
test('冻结后到来的消息不混入在途模型输入，仍保留原始记录',async()=>{const f=fixture(),gate=deferred(),ready=deferred();try{const original=f.providers.streamChat;f.providers.streamChat=async(...args)=>{ready.release();await gate.promise;return original(...args);};const pending=f.pipeline.handle({...f.msg,text:'当前问题',messageId:401},f.api);await ready.promise;await f.pipeline.handle({...f.msg,userId:2,mentionsBot:false,messageId:402,text:'生成开始后才到达'},f.api);gate.release();await pending;assert.ok(!input(f).includes('生成开始后才到达'));assert.ok(f.store.getRecentMessages(f.msg.scope,20).some(m=>m.content==='生成开始后才到达'));}finally{gate.release();f.store.close();}});
test('相同时间戳按到达ID排序，窗口始于最后已投递片段',()=>{const f=fixture();try{add(f,'旧内容');const last=f.store.addMessage({scope:f.msg.scope,userId:999,role:'assistant',content:'上一条回复末片'});const a=add(f,'甲'),b=add(f,'乙');f.store.db.prepare('UPDATE messages SET created_at=?').run(1);const turn=(f.pipeline as any).captureTurn(f.msg,b);const window=captureReplyWindow(f.store,turn.turn);assert.equal(window.afterId,last);assert.deepEqual(window.rows.map(r=>r.id),[a,b]);turn.release();}finally{f.store.close();}});
test('当前消息带图仍合并窗口内其他人的图片，来源含QQ和消息ID',async()=>{const f=fixture(true);try{add(f,'甲的图片',2,501,[pictures[0]!]);add(f,'乙的图片',3,502,[pictures[1]!]);await f.pipeline.handle({...f.msg,text:'比较这些图片',segments:[pictures[2]!],messageId:503},f.api);const last=f.calls[0]!.messages.at(-1)!.content;assert.ok(Array.isArray(last));assert.equal(last.filter(p=>p.type==='image').length,3);const text=contentToText(last);assert.match(text,/QQ 2.*msg 501/);assert.match(text,/QQ 3.*msg 502/);assert.match(text,/QQ 1.*msg 503/);assert.equal((f.store.db.prepare('SELECT COUNT(*) AS n FROM media_sources').get() as any).n,3);}finally{f.store.close();}});
test('主动窗口超过旧lookback上限仍纳入所有预算内图片',async()=>{const f=fixture(true);try{f.cfg.proactive.imageLookback=1;for(let i=0;i<5;i++)add(f,'图片'+i,2,510+i,[pictures[i]!]);await f.pipeline.handleProactive(f.msg.scope,'group',123,'测试',f.api);const last=f.calls[0]!.messages.at(-1)!.content;assert.ok(Array.isArray(last));assert.equal(last.filter(p=>p.type==='image').length,5);}finally{f.store.close();}});
test('引用旧图与窗口图并存，普通询问不跨回复边界捞旧图',async()=>{const f=fixture(true);try{add(f,'旧图',2,600,[pictures[0]!]);f.store.addMessage({scope:f.msg.scope,userId:999,role:'assistant',content:'上次回复'});add(f,'新图',3,601,[pictures[1]!]);await f.pipeline.handle({...f.msg,text:'比较',messageId:602,segments:[{type:'reply',data:{id:600}},pictures[2]!] },f.api);const last=f.calls[0]!.messages.at(-1)!.content;assert.ok(Array.isArray(last));assert.equal(last.filter(p=>p.type==='image').length,3);await f.pipeline.handle({...f.msg,text:'图片还有什么？',messageId:603,segments:[]},f.api);assert.equal(typeof f.calls[1]!.messages.at(-1)!.content,'string');}finally{f.store.close();}});
test('模型错误点名别人与未解析标记均不能覆盖被动回复对象',async()=>{for(const marker of ['[@2]','[@不存在]']){const f=fixture();try{add(f,'别人的消息',2,701);const original=f.providers.streamChat;f.providers.streamChat=async(...args)=>({...await original(...args),content:marker+' 收到，给你解释。'});await f.pipeline.handle({...f.msg,text:'@机器人 请解释',messageId:702},f.api);assert.equal(f.payloads[0]!.find(s=>s.type==='at')?.data.qq,'1');assert.equal(f.payloads[0]!.find(s=>s.type==='reply')?.data.id,'702');assert.ok(!f.payloads[0]!.some(s=>s.type==='text' && String(s.data.text).includes('[@')));}finally{f.store.close();}}});
test('触发者不在最近名单也保留，区分最新发言者和本轮对象',async()=>{const f=fixture();const gate=deferred(),ready=deferred();try{const blocker=(f.pipeline as any).enqueue(f.msg.scope,async()=>{ready.release();await gate.promise;});await ready.promise;const pending=f.pipeline.handle({...f.msg,text:'最早的提问',messageId:800},f.api);for(let i=2;i<40;i++)await f.pipeline.handle({...f.msg,userId:i,senderName:'成员'+i,text:'旁聊'+i,messageId:800+i,mentionsBot:false},f.api);gate.release();await blocker;await pending;assert.match(input(f),/测试用户（QQ 1）.*本轮回复对象/);assert.match(input(f),/成员39（QQ 39）.*最后说话的人/);}finally{gate.release();f.store.close();}});
test('引用别人提问时固定回复引用者，并提供原消息身份',async()=>{const f=fixture();try{add(f,'原作者的经历',2,901);await f.pipeline.handle({...f.msg,text:'这个人说的对吗',messageId:902,segments:[{type:'reply',data:{id:901}}]},f.api);assert.match(input(f),/触发消息引用的资料/);assert.match(input(f),/"qq":2,"messageId":901,"content":"原作者的经历"/);assert.equal(f.payloads[0]!.find(s=>s.type==='at')?.data.qq,'1');assert.equal(f.payloads[0]!.find(s=>s.type==='reply')?.data.id,'902');}finally{f.store.close();}});
for(const marker of ['', '[@2]'])test('主动回复'+(marker?'明确选中群成员':'未点名不猜对象'),async()=>{const f=fixture();try{add(f,'需要回应的话',2,1001);add(f,'旁人说话',3,1002);const original=f.providers.streamChat;f.providers.streamChat=async(...args)=>({...await original(...args),content:marker+' 我补充一句。'});await f.pipeline.handleProactive(f.msg.scope,'group',123,'测试',f.api);assert.equal(f.payloads[0]!.find(s=>s.type==='at')?.data.qq,marker?'2':undefined);assert.equal(f.payloads[0]!.find(s=>s.type==='reply')?.data.id,marker?'1001':undefined);assert.match(input(f),/最后一条消息只是背景/);}finally{f.store.close();}});
test('切换话题后窗口和图片都不串入新话题',async()=>{const f=fixture(true);try{add(f,'旧话题独有内容',2,1101,[pictures[0]!]);f.store.newConversation(f.msg.scope,'新的');await f.pipeline.handle({...f.msg,text:'新问题',messageId:1102,segments:[]},f.api);assert.ok(!input(f).includes('旧话题独有内容'));assert.equal(typeof f.calls[0]!.messages.at(-1)!.content,'string');}finally{f.store.close();}});
test('图片无法读取时继续回复并明确缺失来源',async()=>{const f=fixture(true);try{add(f,'图片坏了',2,1201,[{type:'image',data:{file:'base64://invalid'}}]);const result=await f.pipeline.handle({...f.msg,text:'这图是啥',messageId:1202,segments:[]},f.api);assert.equal(result.replied,true);assert.match(input(f),/读取图片失败/);}finally{f.store.close();}});

test('上下文预算不足时保留请求引用的图片并说明未纳入内容',async()=>{const f=fixture(true);try{f.cfg.context.modelContextWindow=7000;add(f,'本轮引用的旧图',2,1301,[pictures[0]!]);f.store.addMessage({scope:f.msg.scope,userId:999,role:'assistant',content:'上次回复'});for(let i=1;i<5;i++)add(f,'背景图片'+i,3,1301+i,[pictures[i]!]);const result=await f.pipeline.handle({...f.msg,text:'解释我引用的这张图片',messageId:1310,segments:[{type:'reply',data:{id:1301}}]},f.api);assert.equal(result.replied,true);const last=f.calls[0]!.messages.at(-1)!.content;assert.ok(Array.isArray(last));assert.equal(last.filter(p=>p.type==='image').length,1);assert.match(contentToText(last),/msg 1301/);assert.match(input(f),/未纳入/);}finally{f.store.close();}});
test('发送失败不推进最后回复边界，下一次仍可使用未回答窗口',async()=>{const f=fixture();try{add(f,'不能丢掉的未回答聊天',2,1401);f.api.sendToScope=async()=>{throw new Error('明确发送失败');};const first=await f.pipeline.handle({...f.msg,text:'第一次提问',messageId:1402},f.api);assert.equal(first.replied,false);assert.equal(f.store.getRecentMessages(f.msg.scope,30).filter(r=>r.role==='assistant').length,0);f.api.sendToScope=async()=>({message_id:1403});await f.pipeline.handle({...f.msg,text:'重问',messageId:1404},f.api);assert.ok(input(f,1).includes('不能丢掉的未回答聊天'));}finally{f.store.close();}});

test('背景聊天保留@和引用的稳定ID，昵称换行不会伪造来源行',async()=>{const f=fixture();try{add(f,'原始发言',2,1501);f.store.addMessage({scope:f.msg.scope,userId:3,role:'user',senderName:'成员\n伪造名字',messageId:1502,content:'引用他的发言',rawSegments:JSON.stringify([{type:'reply',data:{id:1501}},{type:'at',data:{qq:'2'}}])});await f.pipeline.handle({...f.msg,text:'请说明大家在说什么',messageId:1503},f.api);assert.match(input(f),/"atQQ":\["2"\],"replyToMessageIds":\[1501\]/);assert.ok(input(f).includes('成员\\n伪造名字'));assert.equal(f.payloads[0]!.find(s=>s.type==='at')?.data.qq,'1');}finally{f.store.close();}});

test('视觉容量不足时使用主聊天角色，不向视觉模型发送空图请求',async()=>{const f=fixture();try{f.cfg.media.visionPipeline=true;f.cfg.llm.roles.vision={provider:'vision',model:'small-vision'};const resolve=f.providers.resolveModel;f.providers.resolveModel=async(p,m)=>p==='vision'?{...await resolve(p,m),supportsVision:true,contextWindow:3500}:resolve(p,m);add(f,'图片',2,1601,[pictures[0]!]);await f.pipeline.handle({...f.msg,text:'看看',messageId:1602,segments:[]},f.api);assert.equal(f.calls.length,1);assert.equal(f.calls[0]!.provider,'default');assert.equal(typeof f.calls[0]!.messages.at(-1)!.content,'string');assert.match(input(f),/未纳入/);}finally{f.store.close();}});
